[package]
name = "editor"
version = "0.1.0"
authors = ["Odd-Harald Lillest√∏ Myhren <knarkzel@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.16"
crisp = { path = "../crisp" }

[profile.release]
opt-level = 2
